### ISSUE TITLE
purpose of elastic search

### ISSUE THREAD

**Issue by HelloTo4x** [wolfgarbe/LuceneBench#1]
Hi, can u tell me the purpose of elastic search in this project, does it use for Full-text search

**Comment by wolfgarbe** [comment]
Lucenebench is a benchmark that compares the search performance of Lucene and SeekStorm. 

Elastic search is not directly involved in the benchmark, but Lucene is the core search library used by both Elastic and Solr. Elastic and Solr add an API and a cluster management for distributing an index over multiple servers on top of Lucene.

SeekStorm is a search engine developed from scratch. It doesn't use any other third party libraries apart from zstandard for document compression.

**Comment by HelloTo4x** [comment]
> Lucenebench is a benchmark that compares the search performance of Lucene and SeekStorm.
> 
> Elastic search is not directly involved in the benchmark, but Lucene is the core search library used by both Elastic and Solr. Elastic and Solr add an API and a cluster management for distributing an index over multiple servers on top of Lucene. So it is the other way round, Elastic search uses Lucene, but Lucene doesn't use Elastic elastic search.
> 
> SeekStorm is a search engine developed from scratch. It doesn't use any other third party libraries apart from zstandard for document compression.

Hi, why don't you use Solr ? You mean you use only Cluster multiple server (horizontal scaling) ? So if u don't use Facet, or full text search, why don't you choose other nosql database like Mongo, ....

**Comment by HelloTo4x** [comment]
thanks, sorry, i mean why do you design it faster Lucene with full text search?

**Comment by HelloTo4x** [comment]
No, i mean can u share me your architecture, how can you make it faster than elastic search. thank you

**Comment by wolfgarbe** [comment]
No, I can't share. There is no single single invention which is responsible for the speed advantage. When building a search engine you have to make thousands of design decisions and implementation choices. They influence each other. If combined in the right way small improvements in many components multiply.
